const quizQuestions = [
  { question: "Which dance is traditionally performed during Navratri?", options: ["Garba", "Bhangra", "Kathakali", "Bihu"], answer: "A" },
  { question: "How many nights does Navratri celebrate?", options: ["Seven", "Eight", "Nine", "Ten"], answer: "C" },
  { question: "Which instrument is commonly played during Garba?", options: ["Dhol", "Piano", "Flute only", "Sitar only"], answer: "A" },
  { question: "What is commonly carried while dancing Dandiya?", options: ["Colourful sticks", "Lanterns", "Fans", "Flags"], answer: "A" },
  { question: "Which goddess is worshipped during Navratri?", options: ["Durga", "Saraswati only", "Ganga", "Lakshmi only"], answer: "A" },
];

export const campaignLevelTemplate = [
  {
    levelNumber: 1,
    title: "Follow & Share",
    description: "Connect with Aghori Store on our social media platforms and become part of our community.",
    activityType: "photo_upload",
    points: 100,
    config: {
      sectionTitle: "Social Connect",
      tagline: "Your First Step Starts Here",
      steps: ["Follow Aghori Store on the required social media platform(s).", "Take a screenshot showing that you have followed us.", "Upload the screenshot to complete this challenge."],
      requirement: "A valid follow screenshot is required for verification.",
      hideActivityInstructions: true,
      instructions: "Upload a clear screenshot showing that you follow Aghori Store.",
      maxFileSizeMb: 10,
      allowedTypes: ["image/jpeg", "image/png", "image/webp"],
    },
  },
  {
    levelNumber: 2,
    title: "Mini Game Challenge",
    description: "Put your skills to the test with our interactive mini game. Complete the challenge successfully to move forward.",
    activityType: "memory_game",
    points: 100,
    config: {
      sectionTitle: "Game On",
      tagline: "Play. Complete. Score.",
      steps: ["Start the mini game.", "Complete the given challenge within the required conditions.", "Achieve the required score or objective to complete the level."],
      requirement: "The game must be successfully completed.",
      pairs: 8,
      timerSeconds: 90,
      maxAttempts: 30,
      difficulty: "medium",
      cards: ["🪔", "🥁", "🪘", "💃", "👗", "🌸", "🛕", "🎶"],
    },
  },
  {
    levelNumber: 3,
    title: "Quick Quiz",
    description: "Test your knowledge with a quick five-question quiz. Choose the correct answers and prove your knowledge to unlock the next challenge.",
    activityType: "quiz",
    points: 100,
    config: {
      sectionTitle: "Knowledge Quest",
      tagline: "Think Fast. Answer Smart.",
      steps: ["Read each question carefully.", "Select the answer you believe is correct.", "Answer all five questions.", "Submit your responses to complete the challenge."],
      requirement: "All five questions must be answered correctly.",
      question: quizQuestions[0].question,
      optionA: quizQuestions[0].options[0],
      optionB: quizQuestions[0].options[1],
      optionC: quizQuestions[0].options[2],
      optionD: quizQuestions[0].options[3],
      correctOption: quizQuestions[0].answer,
      questions: quizQuestions,
      passingScore: 5,
    },
  },
  {
    levelNumber: 4,
    title: "Guess the Movie",
    description: "A movie title is hidden behind a series of emojis. Can you decode the clues and identify the correct movie?",
    activityType: "movie_guess",
    points: 100,
    config: {
      sectionTitle: "Emoji Mystery",
      tagline: "Decode the Clues. Name the Movie.",
      steps: ["Carefully observe the emojis displayed on screen.", "Identify the movie they represent.", "Enter your answer in the given field.", "Submit your answer to complete the challenge."],
      requirement: "The correct movie name must be submitted.",
      clue: "👨‍👨‍👦👶🏠😂",
      answer: "Golmaal 3",
      acceptedAnswers: ["Golmaal Three", "Golmaal III"],
      options: [],
    },
  },
  {
    levelNumber: 5,
    title: "Your Favourite Product",
    description: "Explore Aghori Store and choose the product that stands out as your personal favourite.",
    activityType: "photo_upload",
    points: 100,
    config: {
      sectionTitle: "Aghori Favourite",
      tagline: "Show Us What You Love.",
      steps: ["Browse the Aghori Store website.", "Select your favourite product.", "Take a picture or screenshot of the product.", "Upload it to complete the challenge."],
      requirement: "The submitted image must clearly show an Aghori Store product.",
      hideActivityInstructions: true,
      instructions: "Upload a clear picture or screenshot of your favourite Aghori Store product.",
      maxFileSizeMb: 10,
      allowedTypes: ["image/jpeg", "image/png", "image/webp"],
    },
  },
  {
    levelNumber: 6,
    title: "Guess the Music",
    description: "Put your music knowledge to the test. Listen to the short audio clip and identify the song or music featured in the challenge.",
    activityType: "audio_guess",
    points: 100,
    config: {
      sectionTitle: "Music Detective",
      tagline: "Listen Closely. Identify the Tune.",
      steps: ["Play the audio clip provided.", "Listen carefully to the music.", "Identify the song or music.", "Enter your answer and submit it."],
      requirement: "The correct song or music name must be submitted.",
      audioUrl: "",
      prompt: "Listen to the clip and enter the song or tune name.",
      answer: "",
      acceptedAnswers: [],
    },
  },
  {
    levelNumber: 7,
    title: "Discover the Benefits",
    description: "Every product has something valuable to offer. Study the product shown and identify its key benefits.",
    activityType: "text_submission",
    points: 100,
    config: {
      sectionTitle: "Product Expert",
      tagline: "Look Beyond the Product.",
      steps: ["Carefully examine the product image.", "Identify the product and its key benefits.", "Enter or select the relevant benefits.", "Submit your answer to complete the challenge."],
      requirement: "The required product benefits must be correctly identified.",
      hideActivityInstructions: true,
      instructions: "Review the product shown and describe its key benefits in your response.",
      imageUrl: "",
      imageAlt: "Product for the benefits challenge",
      minCharacters: 20,
      maxCharacters: 500,
    },
  },
  {
    levelNumber: 8,
    title: "Spin & Win",
    description: "Take your chance on the wheel and discover the special reward waiting for you.",
    activityType: "spin_wheel",
    points: 100,
    config: {
      sectionTitle: "Lucky Spin",
      tagline: "Your Reward Is One Spin Away.",
      steps: ["Start the Spin the Wheel challenge.", "Spin the wheel once.", "Reveal your reward and coupon code.", "Save your coupon code for your purchase."],
      requirement: "One valid spin is allowed per participant.",
      rewards: ["10% OFF", "15% OFF", "20% OFF"],
      discountPercent: 10,
      wheelTitle: "SPIN TO WIN",
      wheelRibbonText: "FORTUNE WHEEL",
      spinButtonText: "Spin & Win",
      instructions: "Spin once to reveal your reward and coupon code.",
      offerMessage: "Congratulations! Your coupon code is ready to use at checkout.",
    },
  },
  {
    levelNumber: 9,
    title: "Minimum Purchase",
    description: "You are almost at the finish line. Complete your minimum purchase requirement to unlock the final challenge.",
    activityType: "purchase",
    points: 100,
    config: {
      sectionTitle: "Shop & Unlock",
      tagline: "Turn Your Participation Into a Purchase.",
      steps: ["Browse and select any product from Aghori Store.", "Add the product to your cart.", "Complete a purchase of ₹299 or more.", "Keep your order details available for verification."],
      requirement: "A successful purchase with a minimum order value of ₹299 is required.",
      eligibleProductIds: [],
      minimumOrderValue: 299,
      verification: "paid_order",
      instructions: "Complete a paid order of ₹299 or more. Your order will be verified automatically.",
    },
  },
  {
    levelNumber: 10,
    title: "Feedback & Winner Announcement",
    description: "Your journey is almost complete. Share your experience with us and take your place in the final winner announcement.",
    activityType: "text_submission",
    points: 0,
    config: {
      sectionTitle: "Final Celebration",
      tagline: "You Made It to the Final Challenge.",
      steps: ["Share your feedback about the Aghori Store challenge.", "Submit your feedback through the provided form.", "Complete the final participation step.", "Stay connected for the winner announcement."],
      requirement: "Feedback must be submitted successfully to complete the final level.",
      hideActivityInstructions: true,
      instructions: "Share your feedback about the Aghori Store challenge (20–500 characters). See the finalized winners below.",
      minCharacters: 20,
      maxCharacters: 500,
      showWinnerAnnouncements: true,
    },
  },
];
